### ISSUE TITLE
Cannot run `yarn test` after git clone

### ISSUE THREAD

**Issue by ptbrowne** [konnectors/cozy-konnector-template#85]
```
$ yarn test
...
Error: Cannot find module 'rxjs/Rx'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/pbrowne/code/cozy/konn-paybyphone/node_modules/konitor/node_modules/inquirer/lib/ui/prompt.js:3:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by doubleface** [comment]
I cannot reproduce it. Did you run yarn before?

**Comment by ptbrowne** [comment]
Yes :/

```
$ git clone git@github.com:konnectors/cozy-konnector-template.git konn-paybyphone                                                              16:40:16
Cloning into 'konn-paybyphone'...
remote: Counting objects: 1005, done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 1005 (delta 44), reused 67 (delta 29), pack-reused 917
Receiving objects: 100% (1005/1005), 8.93 MiB | 1.22 MiB/s, done.
Resolving deltas: 100% (592/592), done.
 tmp   cd konn-paybyphone/                                                                                                                          16:40:27
$ yarn                                                                                                                       16:40:31
yarn install v1.6.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "cozy-konnector-libs > cozy-client-js@0.9.0" has unmet peer dependency "babel-polyfill@^6.26.0".
[4/4] 📃  Building fresh packages...
✨  Done in 91.86s.
$ yarn test                                                                                                                  16:42:06
yarn run v1.6.0
$ konitor testit .
module.js:538
    throw err;
    ^

Error: Cannot find module 'rxjs/Rx'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/tmp/konn-paybyphone/node_modules/konitor/node_modules/inquirer/lib/ui/prompt.js:3:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by enguerran** [comment]
I ran `npm ls rxjs` on the project to see which package depends on it:

```
❯ npm ls rxjs
cozy-konnector-template@1.0.0 ./cozy-konnector-template
├─┬ konitor@0.8.3
│ └─┬ inquirer@5.2.0
│   └── rxjs@5.5.7
└─┬ webpack-cli@2.1.4
  └─┬ listr@0.14.1
    └── rxjs@6.2.0
```

@ptbrowne Could you check that you have the `rxjs` module in the `node_modules` folder with a `Rx.js` file on it?

```
❯ ls -l node_modules | grep rxjs
drwxr-xr-x - user 29 mai   17:29 rxjs
```
